const GET_USER_PROFILE_START = 'GET_USER_PROFILE_START';
const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

export { GET_USER_PROFILE_START, GET_USER_PROFILE_SUCCESS, GET_USER_PROFILE_FAILURE };
