const SIGN_IN_START = 'SIGN_IN_START';
const SIGN_IN_END = 'SIGN_IN_END';
const SIGN_UP_START = 'SIGN_UP_START';
const SIGN_UP_END = 'SIGN_UP_END';

export { SIGN_IN_START, SIGN_IN_END, SIGN_UP_START, SIGN_UP_END };
